// #region General

// #endregion

import { Metadata } from '@/collections/Caches'

export type SourceMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
export type ValidMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS'
// CONNECT and TRACE are not supported

/* CacheEntry
 */

export type CacheDataEncoding = 'json' | 'text' | 'base64'

export type { Metadata }

export interface CacheMeta {
  // Source Fields
  source_id: string
  key: string // normalized key (e.g., /weather/Shanghai)
  // HTTP Cache Fields
  ttl_s: number // TTL seconds (used for reset/extension)
  etag?: string
  last_modified?: string
  // HTTP Response Fields
  origin_status: number
  data_encoding: CacheDataEncoding // json | text | base64
  content_type?: string // e.g. application/json, image/png
  // Cache Fields
  cached_at: string // ISO time
  expires_at: string | null // ISO time or null (no expiry)
  // stale: boolean // whether expired (server-side view)
}

export interface CacheEntry<D = unknown> {
  data: D | string | null // JSON object, plain text, or base64-encoded
  metadata: Metadata
}

/* Queue Job
 */

export type JobPriority = 'low' | 'normal' | 'high'

export interface RefreshJob {
  id: string // generated by the queue layer
  sourceId: string
  key: string // normalized key
  priority: JobPriority
  attempts: number // number of attempts tried (for consumer retry limit control)
  enqueuedAt: string // ISO time
  sourceMethod: SourceMethod
}

export interface EnqueueResult {
  enqueued: boolean
  reason: 'duplicate' | 'idempotent_reject' | 'invalid' | 'success'
  jobId?: string
}

export interface RateLimitDecision {
  allowed: boolean
  limit: number
  remaining: number
  resetAt: string // ISO time
}

/**
 * Fetch Source Entry Task
 */

export type TaskPriority = 'low' | 'normal' | 'high'

export interface GeneralTask<P = unknown> {
  taskId: string
  priority: TaskPriority
  attempts: number
  createdAt: string // ISO time
  params: P
}

export type AnyTask = GeneralTask<any>

export type FetchSourceEntryParam = {
  sourceName: string
  key: string
}
export type FetchSourceEntryTask = GeneralTask<FetchSourceEntryParam>
