name: buffetd-dev

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5532:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: buffetd
      POSTGRES_USER: buffetd
      POSTGRES_PASSWORD: buffetd

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - '10080:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: f98a66dd772a147c32cff9934791edbda811425f
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6479:6379'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres_data_dev:
