import type { Source, Entry } from '@/payload-types'
import { EntryMetadata } from '@/collections/Entries'

type ExcludePayloadProps<T> = Omit<T, 'id' | 'updatedAt' | 'createdAt'>

export type PureEntry = ExcludePayloadProps<Entry>

export type PureSource = ExcludePayloadProps<Source>

/**
 * General Types
 */
// #region General

export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'CONNECT' | 'TRACE'

export type ValidMethod = Exclude<HTTPMethod, 'OPTIONS' | 'CONNECT' | 'TRACE'>

// #endregion

// #region Entry

export type CacheDataEncoding = 'json' | 'text' | 'base64'

export type { EntryMetadata }

export interface CacheMeta {
  // Source Fields
  source_id: string
  key: string // normalized key (e.g., /weather/Shanghai)
  // HTTP Cache Fields
  ttl_s: number // TTL seconds (used for reset/extension)
  etag?: string
  last_modified?: string
  // HTTP Response Fields
  origin_status: number
  data_encoding: CacheDataEncoding // json | text | base64
  content_type?: string // e.g. application/json, image/png
  // Cache Fields
  cached_at: string // ISO time
  expires_at: string | null // ISO time or null (no expiry)
  // stale: boolean // whether expired (server-side view)
}

export interface CacheEntry<D = unknown> {
  data: D | string | null // JSON object, plain text, or base64-encoded
  metadata: EntryMetadata
}

// #endregion

// #region Task

export type TaskPriority = 'low' | 'normal' | 'high'

export interface GeneralTask<P = unknown> {
  taskId: string
  priority: TaskPriority
  attempts: number
  createdAt: string // ISO time
  params: P
}

export type AnyTask = GeneralTask<any>

export type FetchSourceEntryParam = {
  sourceName: string
  key: string
}
export type FetchSourceEntryTask = GeneralTask<FetchSourceEntryParam>

// #endregion

// #region Job

export type JobPriority = 'low' | 'normal' | 'high'

export interface GeneralJob<P = unknown> {
  jobId: string
  priority: JobPriority
  attempts: number
  createdAt: string // ISO time
  params: P
}

export type AnyJob = GeneralJob<any>

export type FetchSourceEntryJob = GeneralJob<FetchSourceEntryParam>

export interface RefreshJob {
  id: string // generated by the queue layer
  sourceId: string
  key: string // normalized key
  priority: JobPriority
  attempts: number // number of attempts tried (for consumer retry limit control)
  enqueuedAt: string // ISO time
  sourceMethod: ValidMethod
}

export interface EnqueueResult {
  enqueued: boolean
  reason: 'duplicate' | 'idempotent_reject' | 'invalid' | 'success'
  jobId?: string
}

export interface RateLimitDecision {
  allowed: boolean
  limit: number
  remaining: number
  resetAt: string // ISO time
}

// #endregion

// #region Entry

// #endregion
